-- ============================================================
-- AuraGrade — RLS Gap Remediation Migration
-- Run this in your Supabase SQL Editor
-- Generated by Phase C security audit
-- ============================================================

-- ── GAP 1: exception_queue has RLS enabled but ZERO policies ──────────────
-- This means ALL access is denied — backend writes to exception_queue will
-- silently fail (the service_role key bypasses this, but it's still wrong
-- as a schema definition and breaks any anon-key client access).

-- Staff can read exception queue entries
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'exception_queue' AND policyname = 'Staff read exception queue'
  ) THEN
    CREATE POLICY "Staff read exception queue" ON exception_queue
      FOR SELECT USING (
        auth.uid() IN (
          SELECT id FROM profiles WHERE role IN ('ADMIN_COE', 'HOD_AUDITOR', 'EVALUATOR')
        )
      );
  END IF;
END $$;

-- Staff can update exception queue entries (resolve/reject)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'exception_queue' AND policyname = 'Staff update exception queue'
  ) THEN
    CREATE POLICY "Staff update exception queue" ON exception_queue
      FOR UPDATE USING (
        auth.uid() IN (
          SELECT id FROM profiles WHERE role IN ('ADMIN_COE', 'HOD_AUDITOR', 'EVALUATOR')
        )
      );
  END IF;
END $$;

-- Service role (backend) can insert into exception queue — ghost student routing
-- Note: service_role bypasses RLS automatically. This policy is for completeness
-- and to allow future anon-key access if needed.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'exception_queue' AND policyname = 'Backend insert exception queue'
  ) THEN
    CREATE POLICY "Backend insert exception queue" ON exception_queue
      FOR INSERT WITH CHECK (true);
      -- Inserts only happen from backend (service_role), so true is safe here
  END IF;
END $$;


-- ── GAP 2: audit_logs has no INSERT policy ────────────────────────────────
-- The backend (service_role) bypasses this, but adding explicit policies
-- makes the intent clear and protects against future anon-key misuse.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'audit_logs' AND policyname = 'Backend insert audit logs'
  ) THEN
    CREATE POLICY "Backend insert audit logs" ON audit_logs
      FOR INSERT WITH CHECK (true);
      -- Only backend (service_role) writes audit logs — anon clients cannot
  END IF;
END $$;

-- Block UPDATE and DELETE on audit logs — they are append-only
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'audit_logs' AND policyname = 'Deny audit log mutation'
  ) THEN
    CREATE POLICY "Deny audit log mutation" ON audit_logs
      FOR UPDATE USING (false);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'audit_logs' AND policyname = 'Deny audit log deletion'
  ) THEN
    CREATE POLICY "Deny audit log deletion" ON audit_logs
      FOR DELETE USING (false);
  END IF;
END $$;


-- ── GAP 3: Tighten over-permissive "authenticated" read on students ────────
-- Current: ANY authenticated user (including STUDENT role) can SELECT all
-- students via the anon key — this means a logged-in student using the mobile
-- app directly against Supabase could enumerate the full student roster.

-- Drop the broad policy
DROP POLICY IF EXISTS "Authenticated read students" ON students;

-- Replace with: staff see all, students see only themselves
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'students' AND policyname = 'Staff read all students'
  ) THEN
    CREATE POLICY "Staff read all students" ON students
      FOR SELECT USING (
        auth.uid() IN (
          SELECT id FROM profiles
          WHERE role IN ('ADMIN_COE', 'HOD_AUDITOR', 'EVALUATOR', 'PROCTOR')
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'students' AND policyname = 'Student read own record'
  ) THEN
    CREATE POLICY "Student read own record" ON students
      FOR SELECT USING (
        -- Match by email: student's auth email must match their student record email
        email = auth.jwt() ->> 'email'
      );
  END IF;
END $$;


-- ── GAP 4: Tighten over-permissive "authenticated" read on assessments ─────
-- Assessments contain rubric_json and model_answer — this is exam content
-- that students should not be able to read before grading.

DROP POLICY IF EXISTS "Authenticated read assessments" ON assessments;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'assessments' AND policyname = 'Staff read assessments'
  ) THEN
    CREATE POLICY "Staff read assessments" ON assessments
      FOR SELECT USING (
        auth.uid() IN (
          SELECT id FROM profiles
          WHERE role IN ('ADMIN_COE', 'HOD_AUDITOR', 'EVALUATOR', 'PROCTOR')
        )
      );
  END IF;
END $$;


-- ── GAP 5: ledger_hashes needs INSERT policy ──────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ledger_hashes' AND policyname = 'Backend insert ledger hashes'
  ) THEN
    CREATE POLICY "Backend insert ledger hashes" ON ledger_hashes
      FOR INSERT WITH CHECK (true);
  END IF;
END $$;

-- Deny deletion of ledger hashes — they are a tamper-proof audit trail
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ledger_hashes' AND policyname = 'Deny ledger hash deletion'
  ) THEN
    CREATE POLICY "Deny ledger hash deletion" ON ledger_hashes
      FOR DELETE USING (false);
  END IF;
END $$;


-- ── Verification query — run after applying migration ─────────────────────
-- Paste this separately to verify all policies are in place:

/*
SELECT
  tablename,
  policyname,
  cmd,
  qual
FROM pg_policies
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
*/

-- Expected tables with policies after this migration:
-- assessments         → Staff read assessments, Staff manage assessments
-- audit_logs          → Admin read audit logs, Backend insert, Deny update/delete
-- device_push_tokens  → Users manage own, Admin read
-- exception_queue     → Staff read, Staff update, Backend insert
-- grades              → Staff read, Student read own, Staff manage
-- ledger_hashes       → Admin read, Backend insert, Deny deletion
-- profiles            → Users read own, Admin read all, Users update own
-- students            → Staff read all, Student read own, Admin manage
